services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      target: "${MORK_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${MORK_IMAGE_NAME:-mork}:${MORK_IMAGE_TAG:-development}"
    env_file:
      - .env
    ports:
      - "${MORK_SERVER_PORT:-8100}:${MORK_SERVER_PORT:-8100}"
    command:
      - uvicorn
      - "mork.api:app"
      - "--proxy-headers"
      - "--log-config"
      - "logging-config.dev.yaml"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${MORK_SERVER_PORT:-8100}"
      - "--reload"
    volumes:
      - .:/app

  celery:
    build:
      context: .
      target: "${MORK_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    command: ["celery", "-A", "mork.celery_app", "worker", "-l", "DEBUG", "-n", "mork@%h"]
    env_file:
      - .env
    ports:
      - "${MORK_CELERY_SERVER_PORT:-5555}"
    volumes:
      - ./src:/app
    depends_on:
      - api
      - redis

  dockerize:
    image: jwilder/dockerize
