services:
  postgresql:
    image: postgres:12
    env_file:
      - .env

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      target: "${MORK_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${MORK_IMAGE_NAME:-mork}:${MORK_IMAGE_TAG:-development}"
    env_file:
      - .env
    ports:
      - "${MORK_SERVER_PORT:-8100}:${MORK_SERVER_PORT:-8100}"
    command:
      - uvicorn
      - "mork.api:app"
      - "--proxy-headers"
      - "--log-config"
      - "logging-config.dev.yaml"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${MORK_SERVER_PORT:-8100}"
      - "--reload"
    volumes:
      - ./src/app:/app

  celery:
    image: mork:development
    command: ["celery", "-A", "mork.celery.celery_app", "worker", "-l", "DEBUG", "-n", "mork@%h"]
    env_file:
      - .env
    ports:
      - "5555:5555"
    volumes:
      - ./src/app:/app
      - ./bin/seed_edx_database.py:/opt/src/seed_edx_database.py
    depends_on:
      - api
      - redis
      - mailcatcher
      - mysql
      - postgresql

  dockerize:
    image: jwilder/dockerize

  mailcatcher:
    image: sj26/mailcatcher:latest
    ports:
      - "1081:1080"

  mail-generator:
    image: node:20
    user: "${DOCKER_USER:-1000}"
    environment:
      HOME: /tmp
    volumes:
      - ".:/app"
    working_dir: /app/src/mail

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: 
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
