#
# Chart.yaml : métadonnées du chart Helm pour l'application Mork.
# Ce fichier décrit le nom, la version et le but du chart.
#
apiVersion: v2

name: mork
description: Mork, to warn and manage FUN inactive users 
type: application
version: 0.10.0
appVersion: "0.10.0"
